### ISSUE TITLE
[BUG] Fail to parse threshold model from checkpoint

### ISSUE THREAD

**Issue by kaituo** [opendistro-for-elasticsearch/anomaly-detection#314]
**Describe the bug**
When using AES 7.8 or upgrading from 7.8 to 7.9 or during blue/green deployment, I can see the following exception:

```
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2310
	at com.google.gson.stream.JsonReader.expect(JsonReader.java:339) ~[gson-2.1.jar:?]
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322) ~[gson-2.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:168) ~[gson-2.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[gson-2.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176) ~[gson-2.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:755) ~[gson-2.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:721) ~[gson-2.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:670) ~[gson-2.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:642) ~[gson-2.1.jar:?]
	at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.lambda$processThresholdCheckpoint$20(ModelManager.java:523) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.lambda$processThresholdCheckpoint$21(ModelManager.java:523) ~[?:?]
	at java.util.Optional.map(Optional.java:265) ~[?:?]
	at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.processThresholdCheckpoint(ModelManager.java:521) ~[?:?]
	at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.lambda$getThresholdingResult$19(ModelManager.java:490) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.8.0.jar:7.8.0]
	at com.amazon.opendistroforelasticsearch.ad.ml.CheckpointDao.lambda$getModelCheckpoint$2(CheckpointDao.java:137) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.8.0.jar:7.8.0]
	at com.amazon.opendistroforelasticsearch.ad.util.ClientUtil.lambda$asyncRequest$2(ClientUtil.java:140) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:90) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:84) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:261) ~[elasticsearch-7.8.0.jar:7.8.0]
```

**To Reproduce**
I don't have a clear reproduce steps.  Only thing I know is that in AES we use gson 2.1, but we use gson 2.8.6 in ODFE.  When I put them together, I can see the exception.

**Expected behavior**
We cannot run detector normally since checkpoint is messed up.

**Comment by kaituo** [comment]
AD has broken serialization because of a version mismatch between Sifi reader's Gson (2.1) and AD's gson (2.8.6). Since the reader sits on the ES package's root, its gson gets copied to the classpath and used by the parent class loader. Each plugin has its child classloader together with the shared parent classloader. So AD can access both versions of gson. I observe JVM randomly picks one of the two Gson versions. So AD sometimes serializes using one version and deserialize using another version.

I upgraded the Sifi reader's gson version.
