### ISSUE TITLE
Error during build: downloading resources\job-scheduler\opendistro-job-scheduler-1.4.0.0-SNAPSHOT.zip

### ISSUE THREAD

**Issue by amirmuminovic** [opendistro-for-elasticsearch/anomaly-detection#79]
I tried following the instructions to get a running instance of anomaly detection.
I cloned the repository and set the JDK version to be 12.0.2 for environment variable JAVA_HOME.

The build fails with a cryptic message, as follows:

Downloading file://C:\**\anomaly-detection\src\test\resources\job-scheduler\opendistro-job-scheduler-1.4.0.0-SNAPSHOT.zip
Exception in thread "main" java.net.UnknownHostException: C
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
        at java.base/java.net.Socket.connect(Socket.java:585)
        at java.base/sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:961)
        at java.base/sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:923)
        at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1018)
        at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1004)
        at java.base/sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:312)
        at java.base/sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:418)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:381)
        at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:279)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:230)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:217)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integTestCluster#installPlugin'.
> Process 'cmd [/C, call, C:\***\ANOMAL~1\build\cluster\INTEGT~1\ELASTI~1.2\bin\elasticsearch-plugin, install, file://C:\***\anomaly-detection\src\test\resources\job-scheduler\opendistro-job-scheduler-1.4.0.0-SNAPSHOT.zip]' finished with non-zero exit value 1
`

Does anyone have an idea how I could fix this?

**Comment by wnbts** [comment]
i tried build on ubuntu and had no issues. it sounds like a window dns issue.

**Comment by amirmuminovic** [comment]
I'm not sure. I was trying to run an instance of the development branch and got this error.

I tried the same on the opendistro-1.2-alpha and everything worked without an issue.

**Comment by amirmuminovic** [comment]
I had a look at the differences between the development branch and the opendistro-1.2-alpha branch. I noticed that the job scheduler plugin was added. 

The core of my issue seems to be an attempt to download the zip file located in src/test/resources/job-scheduler as a step of the installPlugin step. 

In `build.gradle` in the `ext` object, I changed the value of `job_scheduler_plugin_zip` to the [URL I found on GitHub](https://github.com/opendistro-for-elasticsearch/jobscheduler/releases/download/v1.4.0.0/opendistro-job-scheduler-1.4.0.0.zip) and everything works perfectly now, as shown below:

    ext {
      opendistroVersion = '1.4.0'
      isSnapshot = "true" == System.getProperty("build.snapshot", "true")
      job_scheduler_plugin_zip = "https://github.com/opendistro-for-elasticsearch/job-scheduler/releases/download/v1.4.0.0/opendistro-job-scheduler-1.4.0.0.zip"
    }

**Comment by wnbts** [comment]
thanks for looking into the issue and suggesting the fix!

it looks like the possible root cause might be the path in `build.gradle` is unix-specific with invalid separators for windows. i don't have a windows and therefore cannot reproduce it. but the suggested fix seems reasonable to me. would you care to make a pr?

**Comment by amirmuminovic** [comment]
Thank you for the Help, @wnbts . I have added the necessary change and created a PR.
